// agentq-init.ts — Bootstrapper that sets up a project to use agent-q.
// Installs the local agentqctl CLI, creates agentq/ state, and copies skills.

import { chmod, mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";

/**
 * Core bootstrapper logic. Sets up a project directory for agent-q use.
 * @param sourceDir - Directory containing agentqctl.ts and skills/ (typically the agent-q repo root)
 * @param targetDir - Project root to bootstrap (defaults to "." for CWD usage)
 */
export async function runInit(
  sourceDir: string,
  targetDir = ".",
): Promise<Record<string, unknown>> {
  async function copyDirectoryRecursive(
    source: string,
    destination: string,
  ): Promise<void> {
    await mkdir(destination, { recursive: true });

    const entries = await readdir(source, { withFileTypes: true });
    for (const entry of entries) {
      const sourcePath = `${source}/${entry.name}`;
      const destinationPath = `${destination}/${entry.name}`;

      if (entry.isDirectory()) {
        await copyDirectoryRecursive(sourcePath, destinationPath);
        continue;
      }

      if (entry.isSymbolicLink()) {
        throw new Error(
          `Symlinks are not supported in runtime modules: ${sourcePath}`,
        );
      }

      if (entry.isFile()) {
        const content = await readFile(sourcePath);
        await writeFile(destinationPath, content);
      }
    }
  }

  // ── 1. Locate source files and read version ────────────────────────────

  const sourceAgentqctl = `${sourceDir}/agentqctl.ts`;
  const sourceAgentqctlModules = `${sourceDir}/agentqctl_lib`;
  const sourceSkillsDir = `${sourceDir}/skills`;

  // Read version from source package.json (single source of truth)
  const sourcePackageJson = JSON.parse(
    await readFile(`${sourceDir}/package.json`, "utf-8"),
  );
  const version: string | undefined = sourcePackageJson.version;

  // ── 2. Create state directories (idempotent) ───────────────────────────

  const base = `${targetDir}/agentq`;

  // Create subdirectories (idempotent via recursive: true)
  for (const sub of ["epics", "tasks", "logs"]) {
    await mkdir(`${base}/${sub}`, { recursive: true });
  }

  // Write or update meta.json.
  let stateStatus: "created" | "exists" = "exists";
  const metaPath = `${base}/meta.json`;
  let meta: Record<string, unknown>;
  try {
    meta = JSON.parse(await readFile(metaPath, "utf-8"));
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") {
      meta = { nextId: 1 };
      stateStatus = "created";
    } else {
      throw e;
    }
  }
  if (version) {
    meta.initVersion = version;
  }
  await writeFile(
    metaPath,
    JSON.stringify(meta, null, 2) + "\n",
  );

  // Write .gitkeep files (idempotent — overwrite is fine, they're empty)
  for (const sub of ["epics", "tasks", "logs"]) {
    await writeFile(`${base}/${sub}/.gitkeep`, "");
  }

  // ── 3. Copy/generate tool files (always overwrite) ────────────────────

  const agentqctlSource = await readFile(sourceAgentqctl, "utf-8");
  await writeFile(`${base}/agentqctl.ts`, agentqctlSource);

  // Copy modular agentqctl runtime sources (required by agentqctl.ts imports)
  try {
    await stat(sourceAgentqctlModules);
  } catch {
    throw new Error(
      `Runtime modules directory not found: ${sourceAgentqctlModules}`,
    );
  }
  await copyDirectoryRecursive(sourceAgentqctlModules, `${base}/agentqctl_lib`);

  // Generate agentq/package.json with runtime-only dependencies
  const localPackageJson = {
    dependencies: {
      "minimist": "^1.2.8",
    },
  };
  await writeFile(
    `${base}/package.json`,
    JSON.stringify(localPackageJson, null, 2) + "\n",
  );

  // Generate agentq/agentqctl shell wrapper
  const wrapperContent = `#!/bin/sh
# Generated by agentq-init — do not edit
exec bun run "$(dirname "$0")/agentqctl.ts" "$@"
`;
  await writeFile(`${base}/agentqctl`, wrapperContent);
  // Make wrapper executable (mode 0o755)
  await chmod(`${base}/agentqctl`, 0o755);

  // ── 4. Copy skills (always overwrite) ─────────────────────────────────

  const skills: Record<string, string> = {};

  let skillsDirExists = true;
  try {
    await stat(sourceSkillsDir);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") {
      skillsDirExists = false;
    } else {
      throw e;
    }
  }

  if (skillsDirExists) {
    const entries = await readdir(sourceSkillsDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || !entry.name.startsWith("aq-")) continue;

      const srcFile = `${sourceSkillsDir}/${entry.name}/SKILL.md`;
      const dstDir = `${targetDir}/.claude/skills/${entry.name}`;
      const dstFile = `${dstDir}/SKILL.md`;

      const content = await readFile(srcFile, "utf-8");

      await mkdir(dstDir, { recursive: true });
      await writeFile(dstFile, content);
      skills[entry.name] = "installed";
    }
  }

  // ── 5. Output ─────────────────────────────────────────────────────────

  return {
    state: stateStatus,
    script: "installed",
    wrapper: "installed",
    skills,
    ...(version ? { initVersion: version } : {}),
  };
}

// ── 6. Main entry point ───────────────────────────────────────────────────

if (import.meta.main) {
  const sourceDir = import.meta.dirname;
  if (!sourceDir) {
    console.log(
      JSON.stringify({
        success: false,
        error: "Cannot determine script directory",
      }),
    );
    process.exit(1);
  }
  try {
    const result = await runInit(sourceDir);
    console.log(JSON.stringify({ success: true, ...result }));
  } catch (error) {
    console.log(
      JSON.stringify({ success: false, error: (error as Error).message }),
    );
    process.exit(1);
  }
}
